// <auto-generated />
namespace Mhotivo.Implement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NewUserModifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewUserModifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201510191827528_NewUserModifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
