// <auto-generated />
namespace Mhotivo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _25ds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25ds));
        
        string IMigrationMetadata.Id
        {
            get { return "201503122034073_25ds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
