// <auto-generated />
namespace Mhotivo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UnifiedUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnifiedUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201508101555139_UnifiedUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
